type User {
  _id: ID!
  name: String!
  email: String!
  address: String   
  password: String!  
}

type Device {
  _id: ID!
  name: String!
  type: String!
  brand: String!
  ownerId: ID!
  price: Float!        
  description: String! 
  status: String!
}

type Purchase {
  _id: ID!
  buyerId: ID!
  deviceId: ID!
  timestamp: String!
  price: Float!
}

type Rating {
  _id: ID!
  giverId: ID!
  receiverId: ID!
  rating: Float!
  comment: String
}

type Query {
  users: [User!]!
  user(id: ID!): User
  devices: [Device!]!
  device(id: ID!): Device
  purchases: [Purchase!]!
  purchase(id: ID!): Purchase
  ratings: [Rating!]!
  rating(id: ID!): Rating
  purchasesByUser(userId: ID!): [Purchase!]!
  ratingsByUser(userId: ID!): [Rating!]!
  devicesByBrand(brand: String!): [Device!]!
  devicesByType(type: String!): [Device!]!
  purchaseDetails(purchaseId: ID!): Purchase!
  visibleDevices: [Device!]!
}

type Mutation {
  createUser(input: CreateUserInput!): User!
  createDevice(input: CreateDeviceInput!): Device!
  createPurchase(input: CreatePurchaseInput!): Purchase!
  createRating(input: CreateRatingInput!): Rating!
  deleteDevice(id: ID!): Boolean!
  updateDevice(id: ID!, input: UpdateDeviceInput!): Device!
  updateUser(id: ID!, input: UpdateUserInput!): User!
  changeDeviceStatus(id: ID!, status: String!): Device!
}

input UpdateDeviceInput {
  name: String
  description: String
  brand: String
  price: Float
  type: String
}

input UpdateUserInput {
  name: String
  address: String
}

input CreateUserInput {
  name: String!
  email: String!
  address: String
  password: String!
}

input CreateDeviceInput {
  name: String!
  type: String!
  brand: String!
  ownerId: String!
  price: Float!
  description: String
  status: String
}

input CreatePurchaseInput {
  buyerId: String!
  deviceId: String!
  timestamp: String!
  amount: Float!
}

input CreateRatingInput {
  giverId: String!
  receiverId: String!
  rating: Int!
  comment: String
}

